#!/bin/sh

# Set the path for the generated config file
CONFIG_FILE=/usr/share/nginx/html/config.js

echo "Generating runtime configuration..."

# Create the config file using the original VITE_ variable names as keys.
# Note that the keys are now quoted strings in the JavaScript object.
cat <<EOF > $CONFIG_FILE
window.runtimeConfig = {
  // Client
  "VITE_CLIENT": "${VITE_CLIENT}",

  // Auth Configuration
  "VITE_REDIRECT_URI": "${VITE_REDIRECT_URI}",
  "VITE_CLIENT_ID": "${VITE_CLIENT_ID}",
  "VITE_AUTHORITY": "${VITE_AUTHORITY}",
  "VITE_AUDIENCE": "${VITE_AUDIENCE}",
  "VITE_SILENT_REDIRECT_URI": "${VITE_SILENT_REDIRECT_URI}",

  // App Links
  "VITE_APP_URL": "${VITE_APP_URL}",
  "VITE_ADMIN_URL": "${VITE_ADMIN_URL}",

  // IPSTACK API AND KEYS
  "VITE_IPSTACK_API": "${VITE_IPSTACK_API}",
  "VITE_IPSTACK_ACCESS_KEY": "${VITE_IPSTACK_ACCESS_KEY}",

  // Notifications
  "VITE_NOTIFICATION_HUB": "${VITE_NOTIFICATION_HUB}",

  // For Web3
  "VITE_WALLET_TYPE": "${VITE_WALLET_TYPE}",
  "VITE_ARCANA_CLIENT_ID": "${VITE_ARCANA_CLIENT_ID}",
  "VITE_ARCANA_ID": "${VITE_ARCANA_ID}",
  "VITE_OWNER_ACCOUNT_WALLET_ADDRESS": "${VITE_OWNER_ACCOUNT_WALLET_ADDRESS}",

  // API END POINTS
  "VITE_API_END_POINT": "${VITE_API_END_POINT}",
  "VITE_CORE_API_END_POINT": "${VITE_CORE_API_END_POINT}",
  "VITE_API_PAYMENTS_END_POINT": "${VITE_API_PAYMENTS_END_POINT}",
  "VITE_API_NOTIFICATIONS_END_POINT": "${VITE_API_NOTIFICATIONS_END_POINT}",
  "VITE_API_EXCHANGE_END_POINT": "${VITE_API_EXCHANGE_END_POINT}",
  "VITE_API_BANKS_END_POINT": "${VITE_API_BANKS_END_POINT}",
  "VITE_UPLOAD_API_END_POINT": "${VITE_UPLOAD_API_END_POINT}",
  "VITE_WEB3_API_END_POINT": "${VITE_WEB3_API_END_POINT}",
  "VITE_WEB3_API_EXCHANGE_END_POINT": "${VITE_WEB3_API_EXCHANGE_END_POINT}",
  "VITE_WEB3_API_BANKS_END_POINT": "${VITE_WEB3_API_BANKS_END_POINT}",
  "VITE_API_CARDS_END_POINT": "${VITE_API_CARDS_END_POINT}",
  "VITE_API_LOYALITY_END_POINT": "${VITE_API_LOYALITY_END_POINT}",

  // PAYEES
  "VITE_WEB3_WALLET_ID": "${VITE_WEB3_WALLET_ID}",
  "VITE_TREZOR_EMAIL": "${VITE_TREZOR_EMAIL}",

  // Miscellaneous
  "VITE_NAME": "${VITE_NAME}",
  "VITE_SEND_VERIFICATION_HIDE": "${VITE_SEND_VERIFICATION_HIDE}",
  "VITE_APP_KYC_KYB_PROVIDER": "${VITE_APP_KYC_KYB_PROVIDER}",
  "VITE_APP_SUMSUB_KYB_FLOW": "${VITE_APP_SUMSUB_KYB_FLOW}",
  "VITE_APP_SUMSUB_KYC_FLOW": "${VITE_APP_SUMSUB_KYC_FLOW}",
  "VITE_APP_PAYEE_ON_THE_GO_MODE": "${VITE_APP_PAYEE_ON_THE_GO_MODE}",
  "VITE_NODE_ENV": "${VITE_NODE_ENV}",
  "VITE_APP_EXCHANGE_ON_THE_GO_MODE": "${VITE_APP_EXCHANGE_ON_THE_GO_MODE}",

  // Client Details
  "VITE_CLIENT_NAME": "${VITE_CLIENT_NAME}",
  "VITE_CLIENT_FAVICON": "${VITE_CLIENT_FAVICON}",
  "VITE_CLIENT_META_DESCRIPTION": "${VITE_CLIENT_META_DESCRIPTION}"
};
EOF

echo "Configuration generated. Starting Nginx."

# Start Nginx in the foreground
exec nginx -g 'daemon off;'