export const ApiControllers = {
    customers: "Customer/",
    cards: 'Cards/',
    registration: "Registration/",
    cardsWallet: "CardsWallet/",
    exchangeTransaction: "ExchangeTransaction/",
    security: 'Security',
    exchangeWallets: "ExchangeWallet/",
    common: "Common/",
    notification: "Notification/",
    address: 'Address/',
    addressbook: 'AddressBook/',
    UploadProfile: '/UploadProfile',
    withdraw: "Withdraw/",
    buySell: "Buysell/",
    master: "Master/",
    deposit: "Deposit/",
    markets: "Markets/",
    wallets: "Wallets/",
    dashboard: "Dashboard/",
    partner:"Partner/",
    custodian:"Custodian/",
    exchange:"Exchange/",
    banks:"Banks/",
    transaction:"Transaction/",
    transactions:"Transactions/",
    exchangewallet:"ExchangeWallet/",
    exchangetransaction:"ExchangeTransaction/",
    merchant:"Merchant/",
    payments:"Payments/",
    team:"Team/",
    commissions : 'Commissions/',
    kyc:"kyc",
    kyb:"kyb",
    balance:"balance",
    vaults:"vaults/",
    Uploadprofile:"/uploadprofile"
}