export const textStatusColors = {
  negative: "!text-textLightRed",
  positive: "!text-textGreen",
  active: "!text-textGreen",
  Active: "!text-textGreen",
  "in active": "!text-textLightRed",
  Inactive: "!text-textLightRed",
  inactive: "!text-textLightRed",
  submitted: "!text-textSubmit",
  "not paid": "!text-darkyellowStatus",
  failed: "!text-textLightRed",
  Failed: "!text-textLightRed",
  closed: "!text-closedStatus",
  Closed: "!text-closedStatus",
  approved: "!text-textGreen",
  rejected: "!text-textLightRed",
  "approval in progress": "!text-darkyellowStatus",
  pending: "!text-pendingStatus",
  registered: "!text-darkyellowStatus",
  Registered: "!text-darkyellowStatus",
  Success: "!text-textApproved",
  Submitted: "!text-textSubmit",
  Approved: "!text-textApproved",
  cancelled: "!text-textReject",
  Cancelled: "!text-textReject",
  Rejected: "!text-textReject",
  Pending: "!text-pendingStatus",
  paid: "!text-textGreen",
  Requested: "!text-submiteted",
  Reopened: "!text-submiteted",
  "Partially Paid": "!text-submiteted",
  "partially paid": "!text-submiteted",
};

export const statusDot = {
  approved: "!bg-textGreen",
  cancelled: "!bg-textReject",
  rejected: "!bg-textReject",
  pending: "!bg-pendingStatus",
  closed: "!bg-closedStatus",
  failed: "!bg-textLightRed",
  submitted: "!bg-textSubmit",
  freezed: "!bg-Freezed",
  unfreezed: "!bg-Unfreezed",
  active: "!bg-textGreen",
  inactive: "!bg-textReject",
  suspended: "!bg-textLightRed",
  "freeze pending": "!bg-FreezePending",
  "unfreeze pending": "!bg-UnfreezePending",
  "under maintenance": "!bg-UnderMaintenance",
};
export const AssignedCardsTextStatus = {
  approved: "!text-textGreen",
  cancelled: "!text-textReject",
  rejected: "!text-textReject",
  pending: "!text-pendingStatus",
  closed: "!text-closedStatus",
  failed: "!text-textLightRed",
  submitted: "!text-textSubmit",
  freezed: "!text-Freezed",
  unfreezed: "!text-Unfreezed",
  active: "!text-textGreen",
  inactive: "!text-textReject",
  suspended: "!text-textLightRed",
  "freeze pending": "!text-FreezePending",
  "unfreeze pending": "!text-UnfreezePending",
  "under maintenance": "!text-UnderMaintenance",
};
export const badgeColors = {
  Approved: "!text-paidApproved !border !border-paidApproved",
  Cancelled: "!text-canceled !border !border-canceled",
  approved: "!text-paidApproved !border !border-paidApproved",
  cancelled: "!text-canceled !border !border-canceled",
  Pending: "!text-notPaid !border !border-notPaid",
  pending: "!text-notPaid !border !border-notPaid",
  Submitted:"!text-notPaid !border !border-notPaid",
  submitted: "!text-notPaid !border !border-notPaid",
  Expired:"!text-canceled !border !border-canceled",
  expired: "!text-canceled !border !border-canceled",
};

export const statusColorsPayout = {
  Approved: "!text-textGreen",
  Cancelled: "!text-textReject",
  Rejected: "!text-textReject",
  rejected: "!text-textReject",
  Pending: "!text-pendingStatus",
  pending: "!text-pendingStatus",
  Submitted:"!text-notPaid",
  submitted: "!text-notPaid",
  Expired:"!text-textReject",
  expired: "!text-textReject",
}
